name: Release

on:
  push:
    tags: ['v*']
  workflow_dispatch: # Allows you to trigger the build manually

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-msvc
            release_as: VirtualDesktopAccessor.dll
          - target: aarch64-pc-windows-msvc
            release_as: VirtualDesktopAccessor-aarch64.dll
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      #- name: Configure cache
      #  uses: Swatinem/rust-cache@v2

      - name: Build release DLL
        run: cargo build --release --manifest-path .\dll\Cargo.toml --features multiple-windows-versions,windows-manifest --target ${{ matrix.target }}
        env:
          # https://rust-lang.github.io/rfcs/1721-crt-static.html
          RUSTFLAGS: -C target-feature=+crt-static

      - name: Post Build | Move DLL
        run: |
          mkdir uploads
          mv target/${{ matrix.target }}/release/VirtualDesktopAccessor.dll uploads/${{ matrix.release_as }}

      - name: Post Build | Display structure of uploads folder
        run: ls uploads

      - name: Post Build | Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: dll-${{ matrix.target }}
          path: uploads/*
          retention-days: 1
          if-no-files-found: error

  cbindgen:
    name: Generate C Header
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cbindgen
        run: cargo install cbindgen

      - name: Generate C Header
        run: cbindgen --config ./dll/cbindgen.toml --crate dll --output VirtualDesktopAccessor.h

      - name: Upload C Header
        uses: actions/upload-artifact@v4
        with:
          name: release_c_header
          path: VirtualDesktopAccessor.h
          retention-days: 1
          if-no-files-found: error

  release:
    name: Release
    runs-on: windows-latest
    needs: [build, cbindgen]
    permissions:
      contents: write
    steps:
      - name: Download files from previous jobs
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls artifacts

      # Upload release asset:  https://github.com/actions/upload-release-asset
      # which recommends:      https://github.com/softprops/action-gh-release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: artifacts/*

